# Generated by Django 4.0 on 2021-12-22 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tagslug',
            new_name='name',
        ),
    ]
